version: '3.8'

services:
  emotion-analysis:
    build: .
    platform: linux/amd64
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SUPABASE_URL
      - SUPABASE_KEY
      - SUPABASE_SERVICE_KEY
    restart: unless-stopped
